config/routes.rb
Rails.application.routes.draw do
  devise_for :users, defaults: { format: :html },
                         controllers: {
                         sessions: 'users/sessions'
                        }

  get 'sign_in', to: 'users/sessions#new'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :likes, only: [:create]

  namespace :api, :defaults => {:format => :json} do
      #post '/auth/login', to: 'authentication#login'
      resources :users, only:[:index, :show, :create] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_three_posts
    posts.where(author_id: self).order('created_at DESC').includes(:author).limit(3)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  respond_to :json
  # before_action :configure_sign_in_params, only: [:create]

  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with(resource) do |format|
      format.html { redirect_to after_sign_in_path_for(resource) }
      format.json { render json: { message: 'Logged in.' }, status: :ok }
    end
  end

  private

  def respond_to_on_destroy
    respond_to do |format|
      format.html { redirect_to after_sign_out_path_for(resource_name) }
      format.json { current_user ? log_out_failure : log_out_success }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @title = 'List of users'
    @users = User.all.order(id: :asc)

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    @comment = Comment.new
    @title = "Detail of #{@user.name}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container py-3">
  <div class="row">
    <% @users.each do |user| %>    
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card shadow mb-3">
          <div class="card-body p-2">
            <%= link_to user, class: 'd-flex align-items-center text-decoration-none' do %>
              <img  
                src="<%=user.photo || image_url('empty_user.png') %>"
                alt="<%=user.name %>"
                title="<%=user.name %>"
                class="me-2 user-image img-link"
              />
              <h5 class="card-title m-0 p-0 title-link"><%=user.name %></h5>
            <% end %>
            <p class="card-text text-secondary fst-italic mb-1 me-2 p-0 position-absolute bottom-0 end-0">
              Posts: <%=user.posts_counter %>
            </p> 
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container py-3">
  <%=link_to '< Back to Users', users_url, class: 'title-link' %>

  <div class="card shadow user-card">
    <div class="card-body p-2">
      <img src="<%=@user.photo || image_url('empty_user.png') %>" alt="<%=@user.name %>" title="<%=@user.name %>" class="user-image user-image-profile" />
      <h3 class="card-title"><%=@user.name %></h3>
      <hr class="mt-4" />
      <h5 class="card-title">Bio</h5>
      <p class="card-text"><%=@user.bio %></p> 
    </div>
  </div>

  <div class="row my-3">
    <div class="col-6">
      <h5>Posts (<%=@user.posts_counter %>)</h5>
    </div>
    <div class="col-6 text-end">
      <%=
        link_to 'Create',
        new_post_path,
        class: 'btn btn-sm btn-primary',
        role: 'buton'
      %>
    </div>    
  </div>

  <% @user.last_three_posts.each do |post| %>
    <div class="card shadow mb-3">
      <div class="card-body p-2">
        <h5 class="card-title m-0 p-0 fw-bold">
          <%= link_to post.title, user_post_path(post.author, post), class: 'title-link' %>
        </h5>
        <p class="card-text m-0 p-0"><%=post.text[0...100] %>...</p>
        <p class="card-text text-secondary fst-italic text-end mb-0">
          Comments: <%=post.comments_counter %> | Likes: <%=post.likes_counter %>
        </p>
        <div class="position-absolute top-0 end-0 mt-2 me-2">
          <% if can? :destroy, post %>
            <%= button_to post_path(post), { method: :delete, data: { turbo: false }, class: 'btn btn-link'} do %>
              <i class="fas fa-trash-alt" title="Delete Post"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>   
  <% end %>

  <div class="text-center mt-5">
    <%= link_to 'See All Posts', user_path(@user) + "/posts", class: 'btn btn-outline-dark', role: 'button' %>
  </div>
</div>