config/routes.rb
Rails.application.routes.draw do
  devise_for :users, defaults: { format: :html },
                         controllers: {
                         sessions: 'users/sessions'
                        }

  get 'sign_in', to: 'users/sessions#new'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new, :create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :likes, only: [:create]

  namespace :api, :defaults => {:format => :json} do
      #post '/auth/login', to: 'authentication#login'
      resources :users, only:[:index, :show, :create] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :increment_post_counter
  after_destroy :decrement_post_counter

  def recent_comments
    comments.where(post_id: self).includes(:author).order('created_at DESC').limit(5)
  end

  private

  def increment_post_counter
    author.increment!(:posts_counter)
  end

  def decrement_post_counter
    author.decrement!(:posts_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  # load_and_authorize_resource

  # before_action :authorize_request

  def index
    @posts = Post.where(author_id: params[:user_id])
    render json: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author)
    @title = "Post of #{@user.name}"

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:author)
    @title = "Detail of #{@post.title}"
  end

  def new
    @post = Post.new
    @title = 'Create post'
  end

  def create
    @post = current_user.posts.new(strong_params)
    redirect_to user_path(current_user) if @post.save
  end

  def destroy
    Post.destroy(params[:id])
    redirect_to user_path(current_user)
  end

  rescue_from CanCan::AccessDenied do
    redirect_to '/sign_in'
  end

  private

  def strong_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <div class="mt-3">
    <%=form.label :title, class: 'form-label' %><br>
    <%=form.text_field :title, :required => true, class: 'form-control' %>
  </div>
  <div class="mt-3">
    <%=form.label :text, class: 'form-label' %><br>
    <%=form.text_area :text, :required => true, class: 'form-control no-resize' %>
  </div>
  <div class="mt-4 text-end">
    <%= link_to :back, class: 'btn btn-outline-primary', role: 'button' do %>
      <i class="fas fa-chevron-left me-2"></i>
      Back
    <% end %>

    <%= button_tag type: 'submit', class: "btn btn-primary ms-3" do %>
      Save
      <i class="fas fa-save ms-2"></i>
    <% end %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container py-3">
  <%=link_to '< Back to user', user_url(@user), class: 'title-link' %>

  <div class="card shadow user-card">
    <div class="card-body p-2">
      <img src="<%=@user.photo || image_url('empty_user.png') %>" alt="<%=@user.name %>" title="<%=@user.name %>" class="user-image user-image-profile" />
      <h3 class="card-title"><%=@user.name %></h3>
    </div>
  </div>

  <h5 class="my-3">Posts (<%=@user.posts_counter %>)</h5>

  <% @posts.each do |post| %>
    <div class="card shadow mb-3">
      <div class="card-body p-2">

        <p class="card-text text-secondary fst-italic position-absolute top-0 end-0 me-2 mt-2">
          Likes: <%=post.likes_counter %>
        </p>

        <h5 class="card-title m-0 p-0 fw-bold">
          <%= link_to post.title, user_post_path(post.author, post), class: 'title-link' %>
        </h5>

        <p class="card-text"><%=post.text %></p>

        <hr class="mt-4" />
        <span class="badge bg-secondary my-3">Comments (<%=post.comments_counter %>)</span>

        <!-- Comments list -->
        <% post.recent_comments.each do |comment| %>
          <div class="mb-3">
            <p class="card-title m-0 p-0 fw-bold"><%=comment.author.name %></p>
            <p class="card-text m-0 p-0"><%=comment.text %></p>
          </div>
        <% end %>

      </div>
    </div>
  <% end %>
    <div class="text-center mt-5">
    <%= link_to 'Pagination', "/", class: 'btn btn-outline-dark', role: 'button' %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container py-3">
  <h3>Create Post</h3>
  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="container py-3">
  <%=link_to '< Back to user', user_url(@post.author), class: 'title-link' %>

  <div class="card shadow user-card">
    <div class="card-body p-2">
      <%= form_with url: '/likes', class: 'd-flex w-auto position-absolute top-0 end-0 me-2 mt-2' do |form| %>
        <span class="text-secondary fst-italic">Likes: <%=@post.likes_counter %></span>
        <input type="hidden" name="post" value="<%=@post.id %>">
        <button type="submit" class="btn btn-link p-0">
          <i class="fas fa-heart fs-3 ms-2" title="Like"></i>
        </button>
      <% end %> 
      <h3 class="card-title"><%=@post.title %></h3>
      <p class="card-text"><%=@post.text %></p>

      <hr class="mt-4" />

      <%= form_with model: @comment, url: '/comments' do |form| %>
        <input type="hidden" name="post" value="<%=@post.id %>">
        <div class="input-group mb-3">
          <%=
            form.text_field :text,
            :required => true,
            class: 'form-control',
            placeholder: 'Enter a new comment'
          %>
          <%= button_tag type: 'submit', class: "btn btn-primary" do %>
            Save
            <i class="fas fa-save ms-2"></i>
          <% end %>
        </div>
      <% end %> 

      <span class="badge bg-secondary my-3">Comments (<%=@post.comments_counter %>)</span>      

      <% @comments.each do |comment| %>
        <div class="mb-3 position-relative">
          <p class="card-title m-0 p-0 fw-bold"><%=comment.author.name %></p>
          <p class="card-text m-0 p-0"><%=comment.text %></p>
          <div class="position-absolute top-0 end-0 mt-2 me-2">
            <% if can? :destroy, comment %>
              <%= button_to comment_path(comment), { method: :delete, data: { turbo: false }, class: 'btn btn-link'} do %>
                <i class="fas fa-trash-alt" title="Delete Comment"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>